stages:
  - build
  - unit_tests
  - deploy_staging
  - e2e_tests
  - deploy_prod

build:
  stage: build
  image: node:6.14.0
  when: always
  cache:
    paths:
      - node_modules # NPM packages
      - functions/node_modules
      - .yarn
  artifacts:
    expire_in: 2 weeks
    paths:
      - node_modules # keep as artifact for future jobs
      - functions/node_modules # keep as artifact for future jobs
      - dist
      - functions/mochawesome-report
      - functions/dist
  script:
    - yarn config set cache-folder .yarn
    - yarn install
    - yarn add firebase-ci
    - yarn install --cwd functions
    - npm run build:config # create env specific src/config.js
    - npm run lint
    - npm run build

unit_tests:
  stage: unit_tests
  image: node:6.14.0
  when: on_success
  allow_failure: true
  except:
    - prod
  # Did not load function node modules from previous job
  # cache:
  #   policy: pull # only pull cache, skip uploading
  #   paths:
  #     - node_modules # NPM packages
  #     - functions/node_modules
  #     - .yarn
  artifacts:
    expire_in: 2 weeks
    paths:
      - functions/mochawesome-report
  script:
    - npm run test --prefix functions

deploy_staging:
  stage: deploy_staging
  image: node:6.14.0
  environment:
    name: staging
    url: https://fireadmin-stage.firebaseapp.com
  when: on_success
  only:
    - master
    - web
  script:
    - npm run deploy

e2e_tests:
  stage: e2e_tests
  image: cypress/base
  environment:
    name: staging
    url: https://fireadmin-stage.firebaseapp.com
  when: on_success
  only:
    - master
    - web
    - schedules
  artifacts:
    expire_in: 2 weeks
    paths:
      - cypress/videos
      - cypress/screenshots
  script:
    - echo "Creating cypress.env.json..."
    - 'echo "{ \"FIREBASE_TOKEN\"\: $STAGE_FIREBASE_TOKEN }" > ./cypress.env.json'
    - echo "cypress.env.json created successfully. Calling npm install..."
    - npm run test:stage

deploy_prod:
  stage: deploy_prod
  image: node:6.14.0
  environment:
    name: production
    url: https://fireadmin.io
  when: manual
  only:
    - prod
    - web
  variables:
    TRAVIS_BRANCH: stage # workaround to get firebase-ci to use config for stage from .firebaserc
  script:
    - npm run clean # remove existing dist folder
    - npm run build:config # create env specific src/config.js
    - npm run build # rebuild bundle with new config
    - npm run deploy
