dist: trusty

sudo: false

language: node_js

node_js:
 - 6.11.5 # runtime used within Firebase functions

notifications:
  email:
    on_failure: change
    on_success: change

branches:
  only:
    - master
    - stage
    - prod

cache:
  # bundler: true
  yarn: true
  directories:
    - node_modules # NPM packages

script:
  - npm i -g firebase-ci
  - firebase-ci createConfig
  - npm run lint
  - npm run test
  - npm run build

addons:
  code_climate:
    repo_token: $CODE_CLIMATE

after_success:
  - firebase-ci deploy -s # deploy without CI actions since createConfig is called earlier
