language: node_js
node_js:
  - "0.12"
  - "io.js"
branches:
  only:
    - master
sudo: false
script: "gulp test"
addons:
  code_climate:
    repo_token: 27e0fa94176ed51872ceeeb1f4f688d6738dd51310babc44c9309201ba2d84c2
